# database container
db:
  image: mysql
  ports: 
    - "43306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=password

# application container
app:
  image: tomcat
  ports:
    - "48080:8080"

# web container
web:
  image: nginx
  ports:
    - "40080:80"

